### ISSUE TITLE
fails in windows

### ISSUE THREAD

**Issue by roberts81** [yaniv-aknin/django-ajaxerrors#1]
line 35 of ajaxerrors/middleware.py:  
     if not os.path.isfile(token_path) or not os.stat(token_path).st_uid == os.getuid():

I get the following when running in windows:

AttributeError at /ajax-errors

'module' object has no attribute 'getuid'
Request Method: GET
Request URL:    http://192.168.1.141:8000/ajax-errors?token=6ec7cdeb2634d874f63374d6c387f280
Django Version: 1.3
Exception Type: AttributeError
Exception Value:    

'module' object has no attribute 'getuid'
Exception Location: C:\Python27\lib\site-packages\ajaxerrors\middleware.py in process_request, line 35
Python Executable:  C:\Python27\python.exe
Python Version: 2.7.2

Apparently, os.getuid() is not supported in windows . . .  see http://adminsgoodies.com/crossplatform-way-to-check-admin-rights-in-python-script/  

I may fork and try to do a fix on this if i get time, but may not get to it.

**Comment by yaniv-aknin** [comment]
Sorry, I don't intend to support Windows at this time.

I'll take a look later and see if there's some metadata (setup.py, README,
etc) I should change to make it more apparent.

I will appreciate patches for a fix though, if you'll get to it.

On Thu, Feb 2, 2012 at 7:22 AM, roberts81 <
reply@reply.github.com

**Comment by roberts81** [comment]
Thanks for the quick response . . . guess I'll have to make sure the app is disabled in the settings files for any of our windows developers for now.  Cool app though.
